### DISCUSSION TITLE
Unknown Diagnostics key 'UnusedIncludes'

### DISCUSSION THREAD

**Discussion by juxeii** [clangd/clangd#1065] [Q&A] [answered]
I have this in`.clang` config file:
```
If:                               
  PathExclude: [CP-RT/*, CP-NRT/*]
CompileFlags:
  Remove: -fno-ipa-sra
Diagnostics:
  UnusedIncludes: Strict
```
Visual Studio Code reports `Unknown Diagnostics key 'UnusedIncludes'`.
Is the unused includes feature still active?
How can I fix this?

**Comment by HighCommander4** [comment, marked as answer]
`UnusedIncludes` is new in clangd 14, so the most likely explanation is you're using an older version of clangd.

**Reply by juxeii** [reply]
Right, I am on 13. Sorry :(

**Reply by Freed-Wu** [reply]
Is there any method to check `~/.config/clangd/config.yaml` from command line? I have a 16.0.6 clangd but still have this warning. So I want to check `clangd` from command line.

![screen-2023-11-13-14-10-35](https://github.com/clangd/clangd/assets/32936898/f576eeab-0b40-4deb-99a0-75959dfb744e)

**Reply by HighCommander4** [reply]
@Freed-Wu `UnusedIncludes` is a nested key under `Diagnostics`, please see the example at https://clangd.llvm.org/config.html#unusedincludes.

**Reply by Freed-Wu** [reply]
Thanks! And is it possible to let clangd config support escape enviroment variable? Such as

```yaml
CompileFlags:
  Add:
    - -I${HOME}/.local/include
```
