### DISCUSSION TITLE
Suppressing diagnostics does not work as expected

### DISCUSSION THREAD

**Discussion by alexcocinda** [clangd/clangd#1135] [Q&A] [answered]
I am getting these two errors, but my project builds fine:
```
Unknown argument: '-forward-unknown-to-host-compiler'                       
[clang: drv_unknown_argument]                                               
───────────────────────────────────────────────────────────
Unsupported option '--generate-code=arch=compute_75,code=[compute_75,sm_75]'
[clang: drv_unsupported_opt]                                                
```
I tried to disable them with the following `.clangd` config:

```
CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda-11.4
    - --cuda-gpu-arch=sm_75
    - -L/usr/local/cuda-11.4/lib64
    - -I/usr/local/cuda-11.4/include
Diagnostics:
  Suppress:
    - drv_unknown_argument
    - drv_unsupported_opt
```
I am running on Ubuntu 20.04 with clangd 14.0.0. Am I missing something?
