### DISCUSSION TITLE
Clangd configuration for a specific compiler

### DISCUSSION THREAD

**Discussion by ngunderson** [clangd/clangd#1147] [General]
Is it possible to make conditional configuration based on the compiler?

For example can I have a configuration file like...
```
If: compiler: *qcc
  CompileFlags:
      Add: ['-DFoo']

If: compiler: *clang
  CompileFlags:
      Add: ['-DBlah']
```
