### DISCUSSION TITLE
Use .clangd config file to add include files to source files not in compile_commands.json

### DISCUSSION THREAD

**Discussion by thermopyle** [clangd/clangd#1374] [Q&A] [answered]
At my work we have a large code base that uses a home-grown variant of unity builds; we have a number of `*_package.cpp` files which includes a bunch of related source files. The `*_package.cpp` files are the ones that are added to the project and shows up in generated `compile_commands.json` (I use `xcpretty` to generate a compile_commands.json from a Xcode project). This means the actual source files are not present in the `compile_commands.json` DB. This mostly works with clangd, clangd seem to have a way of "inferring" the actual build command to use for the source file by somehow looking in compile_commands.json.

One problem I have is that sometimes there are headers missing in a source file which makes clangd parsing fail. The header might be missing in the actual source file but are present in the `*_package.cpp` file where the source file is included or in another file included in the `*_package.cpp` file. Anyhow, clangd is unaware of these headers and parsing fails.

I'm trying to use the `.clangd `configuration file to add these headers for the source files that are suffering from this problem. I do this with a statement looking like this;
```
If:
  PathMatch: Reason/Devices/Plugin/PlugHost/VST3Plug\..+
CompileFlags:
  Add: [-include Plugin/PlugHost/PlugProperties.h, -include Core/Thread/LockFreeShare.h]

```
It does not work, however. I suspect the reason is that the source file is not present in the `compile_commands.json` (the source file is included in a `*_package.cpp` file which is present in the DB) and therefor clangd does not add these include files when indexing the file. Is this correct? Is there another way to add include files when clangd indexes a source file?

**Comment by i-ky** [comment, marked as answer]
My guess is that the problem may be in YAML syntax. The following part:
```yaml
CompileFlags:
  Add: [-include Plugin/PlugHost/PlugProperties.h, -include Core/Thread/LockFreeShare.h]
```
is equivalent to:
```yaml
CompileFlags: 
  Add: 
    - "-include Plugin/PlugHost/PlugProperties.h"
    - "-include Core/Thread/LockFreeShare.h"
```
i.e. you are passing pairs of flags as one. Can you please try the following?
```yaml
CompileFlags:
  Add: [-include, Plugin/PlugHost/PlugProperties.h, -include, Core/Thread/LockFreeShare.h]
```
which would be equivalent to:
```yaml
CompileFlags: 
  Add: 
    - "-include"
    - Plugin/PlugHost/PlugProperties.h
    - "-include"
    - Core/Thread/LockFreeShare.h
```
