### DISCUSSION TITLE
Exclude specific files via argument like VSCode 'search.exclude'

### DISCUSSION THREAD

**Discussion by amordo** [clangd/clangd#1382] [Ideas]
Project with multiple API versions has identical symbols. It'll be cool to have some setting like:
```
"clangd.exclude": {
    "**/api_v*": true,
}
```

**Comment by HighCommander4** [comment]
You can do this with a [clangd config file](https://clangd.llvm.org/config.html) today. Something like:

```yaml
If:
  PathMatch: .*/api_v*

Index:
  Background: Skip
```
