### DISCUSSION TITLE
How to disable vector inlinehints?

### DISCUSSION THREAD

**Discussion by Michaelzhouisnotwhite** [clangd/clangd#1470] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/52443370/213720417-1c6dac8c-c67b-45bd-ac55-a0653053d7b2.png)

There is no option in .clangd configration to disable `[0]=`，`[1]=` etc.

**Comment by sam-mccall** [comment, marked as answer]
These are designator hints, and are controlled by `Designators` which is missing from the docs :-(

**Reply by Michaelzhouisnotwhite** [reply]
I add `Designators: false` under Inlayhints. It works!
```yaml
InlayHints:
  Designators: false
  ParameterNames: true
  DeducedTypes: true
  Enabled: true
```
