### DISCUSSION TITLE
How to add OS-specific complier flags in .clangd file?

### DISCUSSION THREAD

**Discussion by ChenZhongPu** [clangd/clangd#1602] [Q&A]
I configured `clangd` using nvim-lspconfig. Now I would like to enable `AVX` support for certain projects in Linux.

How can I detect OS type in `.clangd` file, and then add -mavx flag *only* when it is Linux?

```yaml
CompileFlags:
  Add: [-xavx]
```

**Comment by i-ky** [comment]
> for certain projects

You can add such fragment (part, separated by `---`) to the end of your global config file:
```yaml
---
If:
  PathMatch:
  - /path/to/project1/.*
  - /path/to/project2/.*
CompileFlags:
  Add: [-xavx]
```
Or add project-level `.clangd` files.

**Reply by ChenZhongPu** [reply]
The project is expected to be built on both macOS (aarch64) and Linux, and I would like to add `-mavx` flag **only** on Linux.

**Reply by i-ky** [reply]
I would suggest splitting configuration into multiple fragments like so:
```yaml
# common options for Linux and macOS
---
# options for Linux
CompileFlags:
  Add: [-xavx]
---
# options for macOs
```
...and then commenting/uncommenting fragments as needed depending on the situation.

See also #1504.
