### DISCUSSION TITLE
'Failed to load shard' errors

### DISCUSSION THREAD

**Discussion by vincentjgoh** [clangd/clangd#1830] [General]
I just started using clangd 17 instead of 14, with LSP mode in emacs. 

I'm working on an Unreal project, and it appears that in general it 'prefers' v14, but I was hoping a newer version would help with issues where an excessive amount of memory (~80GB) is used, starving out other processes. (That may still happen, but I wanted to at least try with a newer version before complaining.)

In any case, pointing LSP-clangd at a different executable has generated an enormous number of messages like this in the stderr stream:

```
E[18:06:17.983] Error while reading shard D:\p4v\Dev\Engine\Source\Runtime\CoreUObject\Private\Internationalization\PackageLocalizationUtil.cpp: wrong version: want 18, got 17
V[18:06:17.983] Failed to load shard: D:\p4v\Dev\Engine\Source\Runtime\CoreUObject\Private\Internationalization\PackageLocalizationUtil.cpp
```

I haven't been able to find anything online about what this error means or how to fix it other than to regenerate the compile_commands.json and delete the .clangd file in that directory.

Unreal generates the compile_commands.json file for me, and like I said, it's kind of assuming that I'll be using clang 14 (though I hear that's been bumped up to v16 in UE5.3). 

My .clangd file isn't anything interesting either.

```
CompileFlags:
    Remove: -W*
    Add: -I="d:/p4v/Dev/Engine/Source/Runtime/Core/Public/"

Diagnostics:
    Suppress: "*"

Index:
    Background: Build
```

Any advice?
