### DISCUSSION TITLE
How to specify the format call of clangd in VSC?

### DISCUSSION THREAD

**Discussion by juxeii** [clangd/clangd#1833] [Q&A]
I would like to use the formatter of the clangd extension in VSC.
On default it formats the file, but not the way I want.
Is there a way to specify the entire command, like:
`clang-format-9 -style=file -i ${file}`

How can I do that?

**Comment by i-ky** [comment]
No, there is no way to specify `clang-format` command, because `clangd` does not use `clang-format` binary, it uses a [formatting library](https://clang.llvm.org/docs/LibFormat.html) instead. However, `clangd` should respect style options if you put them in [`.clang-format` file](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configuring-style-with-clang-format) in one of the ancestor directories of the file you want to format.

**Comment by juxeii** [comment]
Thx for the info. But it seems the `.clang-format` file is ignored. I created one in the project root, but whatever I change it does not make any difference. Is there a way for a more verbose output to see which configuration setting are active?

**Reply by HighCommander4** [reply]
Please see https://clangd.llvm.org/troubleshooting#gathering-logs fow hoe to collect verbose logs.

It would also help to provide a piece of example code, and indicate the actual vs. expected formatting.

**Comment by juxeii** [comment]
I have to correct me. The .clang-format file is indeed applied if `clangd` formats files.
But if I call `clang-format-9` directly, it gives a different formatting.

One result snippet of `clang-format-9 -style=file somefile.cpp` is
```cpp
return types::CellDynamicParams{std::optional<types::nr_rrc::MeasurementTimingConfiguration>{mtc},
                                    std::nullopt,
                                    std::nullopt,
                                    std::nullopt,
                                    servedPlmnList,
                                    std::nullopt};
```
Whereas clangd does
```cpp
return types::CellDynamicParams{
        std::optional<types::nr_rrc::MeasurementTimingConfiguration>{mtc},
        std::nullopt,
        std::nullopt,
        std::nullopt,
        servedPlmnList,
        std::nullopt};
```
The .clang-format file is
```
---
BreakBeforeBraces: Allman
ColumnLimit: 120
IndentWidth: 4
TabWidth: 4
UseTab: Never
---
Language: Cpp
AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignOperands: false
AlignTrailingComments: false
AlignEscapedNewlinesLeft: true
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortIfStatementsOnASingleLine: true
AllowShortLoopsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Inline
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: None
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: true
BreakStringLiterals: true
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DisableFormat: false
FixNamespaceComments: true
IncludeCategories:
  - Regex:           '^<sys/'
    Priority:        1
  - Regex:           '^<'
    Priority:        2
  - Regex:           '^"'
    Priority:        3
IndentCaseLabels: true
KeepEmptyLinesAtTheStartOfBlocks: false
MaxEmptyLinesToKeep: 1
BraceWrapping:
   AfterNamespace: false
   AfterUnion: true
NamespaceIndentation: None
PenaltyReturnTypeOnItsOwnLine: 5000
PointerAlignment: Left
SortIncludes: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
Standard: Cpp11
---
Language: Proto
AlwaysBreakAfterReturnType: All
AllowShortFunctionsOnASingleLine: false
```

What could be the reasons, that `clang-format-9` behaves differently?
The enitre project has only this `.clang-format` file.

I then also copied the above style file into several ancestor paths and even into the src folder, but clang-format-9 keeps on doing its own thing applies something different.
