### DISCUSSION TITLE
Slow cuda completion in WSL environment

### DISCUSSION THREAD

**Discussion by Hyiker** [clangd/clangd#1863] [Q&A]
I'm using clangd along with vscode to write some cuda code on my arch WSL. However, I found intellisense engine is slow responding the completion(approximately 5-6 seconds for a single function completion!). It became more instersting when I found the c++ code completion hadn't been effected.
After some deeper digging, it turned out that clangd is probably slown down by searching the windows host files in `$PATH` variables, which all start with `/mnt/`. It worked fine after I remove all those host paths from `$PATH`, but I'd like to remove completion lag while keeping these paths. 
 I'm using configurations listed below:
```
CompileFlags:
  Remove:
    - -forward-unknown-to-host-compiler
    - --generate-code*
    - -rdc=true
    - -gencode
If:
  # remove all windows host files
  PathExclude: /mnt/.*
```
But the `PathExclude` part just didn't solve the problem.

I'm using clangd 16.0.6 and nvcc 12.3, and they all stay in the Linux filesystem.

**Comment by HighCommander4** [comment]
The only effect of `PathExclude` is that it excludes **config file entries** from applying to those paths.

(An example use would be:

```yaml
If:
  PathExclude: /myproject/c-library

CompileFlags:
  Add: [-std=c++20]
```

This has the effect of adding `-std=c++20` to the compile command of every file in the project except those in `/myproject/c-library`.)

> it turned out that clangd is probably slown down by searching the windows host files in `$PATH` variables, which all start with /mnt/. It worked fine after I remove all those host paths from `$PATH`

It's surprising to me that clangd would be looking in `$PATH` during code completion. Perhaps you can use a debugger or profiler to gather more information about what clangd is doing (e.g. get some stack traces during a slow operation)?
