### DISCUSSION TITLE
clang(using_decl_conflict_reverse)

### DISCUSSION THREAD

**Discussion by P2441M** [clangd/clangd#1927] [Q&A]
(First of all, I'm new to clangd😨)
While using Visual Studio Code+clangd, I found that clangd always recognizes my header as a MSVC header file, even though I'm using g++ in CMake (and of course I exported the compile commands).
![image](https://github.com/clangd/clangd/assets/93473486/5b8d50f1-087e-47d8-941f-fc1fc624fc17)
`compile_commands.json`:
```json
[
{
  "directory": "C:/Users/Lenovo/code/C++/OI/build",
  "command": "C:\\msys64\\mingw64\\bin\\g++.exe -g -o CMakeFiles\\OI.dir\\main.cpp.obj -c C:\\Users\\Lenovo\\code\\C++\\OI\\main.cpp",
  "file": "C:\\Users\\Lenovo\\code\\C++\\OI\\main.cpp",
  "output": "CMakeFiles\\OI.dir\\main.cpp.obj"
}
]
```
So I added some including paths in `config.yaml`:
```yaml
CompileFlags:
  Add:
    [-I\msys64\mingw64\include\c++\13.2.0,-I\msys64\mingw64\include\c++\13.2.0\x86_64-w64-mingw32]\
Index:
  StandardLibrary: No    
```

It works, kind of...
When I put my cursor on the header, it shows the correct path, but soon there were some errors prompted:
![image](https://github.com/clangd/clangd/assets/93473486/7172a9bc-d6d4-4142-9cc6-60704aa94645)
The source files in msys conflicted with the one in Windows Kits. What can I do to stop this? 🙇‍♂️ :
