### DISCUSSION TITLE
Disable case check for external headers and sources?

### DISCUSSION THREAD

**Discussion by Stehsaer** [clangd/clangd#1984] [Q&A] [answered]
As the title says, is there a way to disable clang-format feature for external headers and sources, while keeping enabled for my own headers and sources? It really bothers when you browse an external header or source for reference, tons of warnings flood you over.

**Comment by HighCommander4** [comment]
Could you elaborate please about what "case check" you are referring to and how to enable it? A code example always helps.

**Reply by Stehsaer** [reply]
## Clarification
Sorry for the confusion. What I mean is the naming style.
For example:
-  I'm currently using `Leading_upper_snake_case` as class names and `lower_case` for variable names across my whole codebase, but the sources code of external/third-party libraries usually come with different naming style.
- I have clangd's clang-tidy feature turned on:
  ```YAML
  CheckOptions:
        readability-identifier-naming.VariableCase: lower_case
        readability-identifier-naming.ClassCase: Leading_upper_snake_case
        readability-identifier-naming.AbstractClassCase: Leading_upper_snake_case
        readability-identifier-naming.FunctionCase: lower_case
        readability-identifier-naming.MacroDefinitionCase: UPPER_CASE
        readability-identifier-naming.StructCase: Leading_upper_snake_case
        readability-identifier-naming.EnumCase: Leading_upper_snake_case
        readability-identifier-naming.EnumConstantCase: Leading_upper_snake_case
  ```
- When browsing external code, warnings keep popping out suggesting that the external code base is using a different naming style / identifier case style from mine.
## Screenshot for illustrating the problem
### My code
![image](https://github.com/clangd/clangd/assets/54050160/dfcda8eb-9c45-45d3-93ef-415e34ceef7b)
### External Code
![image](https://github.com/clangd/clangd/assets/54050160/8af0a2ad-5f47-4f4e-b336-fa82b1c8fdaf)
