### DISCUSSION TITLE
Am I writing a conditional config correctly?

### DISCUSSION THREAD

**Discussion by recursivenomad** [clangd/clangd#2076] [Q&A] [answered]
I would like to have `MissingIncludes` diagnostics for code that I am composing, but not when browsing system headers or SDK files.

My global `config.yaml` looks like something this:

```yaml
Diagnostics:
  MissingIncludes: Strict
  UnusedIncludes: None

---

If:
  PathMatch: [ /path/to/compiler/.*, /path/to/other/compiler/.*, /path/to/sdk/.* ]

Diagnostics:
  MissingIncludes: None
  UnusedIncludes: None
```

However, this would appear to be identical to only having the first 3 lines.

I have also tried adding the same absolute paths to a `PathExclude:` in the first fragment, as well as swapping hierarchical order of both fragments, but the behaviour is unchanged.

~I know the syntax is correct for the conditional `If`, because it works conditionally when I remove the upper fragment.~  What would the correct syntax be for having files default to one set of diagnostics, and specified files use different diagnostics?
