### DISCUSSION TITLE
I used ``` Diagnostics: Suppress: [‘*’] ``` to disable diagnostics for all files. Do you have a way to disable diagnostics for a specific file?

### DISCUSSION THREAD

**Discussion by Elsa-is-My-Muse** [clangd/clangd#2142] [General]
I used ``` Diagnostics: Suppress: [‘*’] ``` to disable diagnostics for all files. Do you have a way to disable diagnostics for a specific file?

**Comment by HighCommander4** [comment]
[PathMatch](https://clangd.llvm.org/config.html#pathmatch) can be used to limit a section of a config file to apply only to certain source files.

Note that the path which is matched is the path of the source file which is open in the editor. So, you can use this to implement "suppress diagnostics when opening source file A but not source file B", but not "when opening source file A, suppress diagnostics coming from header B but not header C". I'm not aware of a way to do the latter.

**Reply by Elsa-is-My-Muse** [reply]
```
If:
  PathMatch: ".*test\\.cpp"
  Diagnostics:
    Suppress: ".*"
```
I set the MatchPath like this, but it gives an error: Unknown If key 'Diagnostics' clangd-config

**Reply by HighCommander4** [reply]
`Diagnostics` needs to be at the top level.

`If` applies to everything that follows until a `---`, see https://stackoverflow.com/a/76286667 for an example.

**Reply by Elsa-is-My-Muse** [reply]
```
If:
  PathMatch: "include/pubsub/pubsub.h"
Diagnostics:
    Suppress: ".*"

---

If:
  PathMatch: "src/pubsub/pubsub_tiny.c"
Diagnostics:
    Suppress: ".*"
```
Thanks for your reply. I set it up as you suggested, but it didn't work. The above is my .clangd file. The following is my tree path structure of the project.
```
├─include
│  ├─common
│  ├─pubsub
│  ├─rfc3399
│  └─uri
├─src
│  ├─common
│  ├─pubsub
│  ├─rfc3399
│  └─uri
```
