### DISCUSSION TITLE
How to config the `IgnoreHeader`

### DISCUSSION THREAD

**Discussion by LimingFang** [clangd/clangd#2159] [Q&A]
I'm using m2pro, and i have a cpp project which compiles on linux only(e.g. there's some header file difference between these two target platform). But it can do `cmake` successfully on mac so that i can browse code on mac with the compile_commands.json.
Say that _x.h_ includes _common.h_ which includes _tracing.h_, and clangd has an error for _tracing.h_ but it's ok since there's missing type on mac. As a result, clangd also has an error for _x.h_, but i want to suppress it. Here's my config demo:
```
Diagnostics:
    UnusedIncludes: Strict
    MissingIncludes: Strict
    Includes:
        IgnoreHeader:x\.h
```
But it doesn't work.
And here's what i found on clangd website: 
![image](https://github.com/user-attachments/assets/2d86fbb8-ac20-4bce-a790-ea03b21cc1b2)
