### DISCUSSION TITLE
.clangd CompileFlags Add -I flags doesn't work for relative paths

### DISCUSSION THREAD

**Discussion by slmjkdbtl** [clangd/clangd#2191] [Q&A]
My project is like
```
.
├── demo
│   └── hello.c
├── .clangd
└── header.h
```

```c
// demo/hello.c
#include <header.h>
```

```yaml
# .clangd
CompileFlags:
  Add:
    - "-I." # this doesn't work
    - "-I/Users/me/dev/proj" # this works
```

`compile_flags.json` / `compile_flags.txt` all works with relative paths, but `.clangd` only works with absolute paths.

```
$ clangd --version
Apple clangd version 16.0.0 (clang-1600.0.26.3)
Features: mac+xpc
Platform: arm64-apple-darwin24.0.0
```

I'm using clangd with vim + ale
