### DISCUSSION TITLE
If: + CompileFlags:

### DISCUSSION THREAD

**Discussion by bushuyev** [clangd/clangd#2296] [Q&A] [answered]
Hi, I'm trying to set up a toy c++ + cuda [project](https://github.com/bushuyev/cuda_0) in nvim and  need to add cuda flags only for cu files, like this:
```


CompileFlags:
  Remove:
    - -rdc=true
    - --options-file
    - "--generate-code=arch=compute_89,code=[compute_89,sm_89]"
    - -forward-unknown-to-host-compiler
  Add:
    - -std=c++20
    - -I/usr/local/cuda/include
    - -I/usr/include/c++/13
    - -I/usr/include/x86_64-linux-gnu/c++/13
If:
  PathMatch: .*\.cu
CompileFlags:
  Add:
    - –cuda-path=/usr/local/cuda
    - -x cuda
```

but if "If:..." part is added the .clangd config seems to be ignored completely so perhaps there is something wrong with syntax. I've also tried to put options for cu files under If, i.e. adding two tabs before CompileFlags under IF but to no avail. 
Could somebody please give any hints on how to fix it? 

I've also tried to enable logging in nvim-lspconfig like this:

 ```
clangd = {
          filetypes = { "c", "cpp", "cuda", "cu" }, 
          cmd = {
           "clangd",
           "--log=verbose",
         
         },

```

but can't find anything from clang in ~/.local/state/nvim or anywhere else.
