### DISCUSSION TITLE
Help wanted: How to switch different project-level .clangd files for different target? And How dose clangd behave if multiple CompliationDatabase were declared in different fragments?

### DISCUSSION THREAD

**Discussion by zhang-stephen** [clangd/clangd#2326] [Q&A]
I am using VSCode and clangd for a commercial C++ project, which could be compiled for multi-architects:
- Hardware: ARM Cortex-A, RISC-V and something with different ISA might be supported in the future...
- x86_64: for simulation 

For the cross-compilation to the hardware, there would be several `compile_commands.json` generated into different paths:
- `out/build-prod-arm`: for ARM Cortex-A
- `out/build-prod-rv`: for co-processor based on RISC-V
- `out/build-prod-clang64`: for toolkits run on x86, and it is also the compilation output path for x86_64 building.

Then I need a complex project-level `.clangd` looks like this for hardware building shown as below. And I just need the common part for x86_64 building. Then the Question is, how to switch different `.clangd` configurations **conveniently** for similar situations? or are there some suggestions for better practices?

```yaml
--- # Common part, for toolkits and fallback to clang
CompileFlags:
    Add: []
    Remove:
        - -m*
        - -f*
        - -W*
    CompilationDatabase: out/build-prod-clang64

Index:
    StandardLibrary: false

Diagnostics:
    UnusedIncludes: None

--- # for ARM
If:
    PathMatch:
        - app/ctrl
        # ... more paths
CompileFlags:
    Add:
        - -isystem
        - /usr/include/c++/v1/
    CompilationDatabase: out/build-prod-arm

--- # for RV
If:
    PathMatch:
        - app/rv/
CompileFlags:
        CompilationDatabase: out/build-prod-rv
```
----

Update for the 2nd question:

For this example, the fallback would be always effective, the `CompilationDatabase` would be applied for files in the `app/ctrl` and the same field in ARM fragment would be ignored. But I want clangd to parse implementations for ARM only here, how does clangd behave if there were multiple `CompilationDatabse` were declared in different fragments?

An example shown as following:
![image](https://github.com/user-attachments/assets/686fa57f-f77e-4e45-b4d1-d1e3277313b0)

```cpp
constexpr bool isBuildForArm()
{
#ifdef __aarch64__
    return true;
#else
    return false;
#endif // __aarch64__
}
```
