### ISSUE TITLE
Allow specifying more than one compile_commands.json file

### ISSUE THREAD

**Issue by StMartin81** [clangd/clangd#1092]
We have a multi target project and use a Visual Studio Code workspace where we have defined all build targets. When I create a compile_commands.json I have to select for which target I want to create this file. Would it be possible to add an option to clangd so that it is possible to specify additional compilation databases? The behavior I image is the following:
* clangd looks for the compile commands of the source file in the first specified compilation database
* if no commands were found for the source files try the other compilation databases
* use the flags from compile_flags.txt if the file exists and none of the specified compilation databases provided the compile flags for the source file

**Comment by HighCommander4** [comment]
If the source files belonging to the different CDBs are grouped in their own directory, then one way to solve this problem today is to create a [clangd config file](https://clangd.llvm.org/config.html) with multiple [`If`](https://clangd.llvm.org/config.html#if) blocks each specifying a [`CompilationDatabase`](https://clangd.llvm.org/config.html#compilationdatabase).

For example:


```
If:
  PathMath: /project/target1/.*

CompileFlags:
  CompilationDatabase: /project/build/target1

---

If:
  PathMath: /project/target2/.*

CompileFlags:
  CompilationDatabase: /project/build/target2
```

This will make source files in `/project/target1/` use `/project/build/target1/compile_commands.json` and similarly for target2.
