### ISSUE TITLE
Suppressing diagnostics does not work as expected

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#1142]
The suppression filter is added after we run the driver, so driver diagnostics (e.g. `drv_unknown_argument`) cannot be suppressed.

### Discussed in https://github.com/clangd/clangd/discussions/1135

<div type='discussions-op-text'>

<sup>Originally posted by **alexcocinda** May  2, 2022</sup>
I am getting these two errors, but my project builds fine:
```
Unknown argument: '-forward-unknown-to-host-compiler'                       
[clang: drv_unknown_argument]                                               
───────────────────────────────────────────────────────────
Unsupported option '--generate-code=arch=compute_75,code=[compute_75,sm_75]'
[clang: drv_unsupported_opt]                                                
```
I tried to disable them with the following `.clangd` config:

```
CompileFlags:
  Add:
    - --cuda-path=/usr/local/cuda-11.4
    - --cuda-gpu-arch=sm_75
    - -L/usr/local/cuda-11.4/lib64
    - -I/usr/local/cuda-11.4/include
Diagnostics:
  Suppress:
    - drv_unknown_argument
    - drv_unsupported_opt
```
I am running on Ubuntu 20.04 with clangd 14.0.0. Am I missing something?</div>

**Comment by cilence** [comment]
I have the same problem

**Comment by ZJUGuoShuai** [comment]
I have the same problem

**Comment by ZJUGuoShuai** [comment]
From https://github.com/clangd/vscode-clangd/issues/327, it said we can suppress these by adding to your `.clangd` file:

```yaml
CompileFlags:
  Remove:
    - -forward-unknown-to-host-compiler
    - --generate-code*
```
