### ISSUE TITLE
Expand Clangd Configuration to let If match a compiler

### ISSUE THREAD

**Issue by ngunderson** [clangd/clangd#1155]
Based on a discussion, https://github.com/clangd/clangd/discussions/1147, I would like to request an extension to the [if](https://clangd.llvm.org/config#if) configuration based on looking at the compiler. This would also provide functionality in lieu of this issue being resolved, https://github.com/clangd/clangd/issues/533. This could look something like the following:

```
If:
   CompilerMatch: .*qcc   # would pattern match argv[0]

CompileFlags:
   Add: ['-D_QCC_FLAG1', '-D_QCC_FLAG2']
---
```

**Comment by sam-mccall** [comment]
Hmm, this doesn't really fit into how configs interact with compile commands :-(

First the config is compiled and evaluated, then it's used (among other things) to produce the compile flags. Trying to use the compile flags in producing the config adds a circular dependency. This fragment shows the problem:

```
If:
  CompilerMatch: "gcc"
CompileFlags:
  CompilationDatabase: "/path/to/cdb_dir"
```
