### ISSUE TITLE
Signalled during AST worker action: FoldingRanges

### ISSUE THREAD

**Issue by KagaJiankui** [clangd/clangd#1307]
The WSL version of Clangd server crashes frequently on VSCode with remote WSL, especially when analyzing the AST of a file with some obvious semantic error.

Example file:
```cpp
#include <cassert>
#include <complex>
#include <iostream>
#include <regex>
#include <string>
#include <vector>

#include "debug_print.h"
using std::vector;
/**
 * @brief Parse a input string to three parts of an floating point number in scientific expression. Arbitrary precision.
 *
 * @param inputString
 * @param integerPart
 * @param decimalPart
 * @param indexPart
 * @param type
 */
void parseToString(const std::string& inputString, const vector<std::complex<double>>& integerPart, const vector<std::complex<double>>& decimalPart,
                   const vector<std::complex<double>>& exponentialPart, int* type)
{
  std::string integerRegExp       = "([+-]?\\d+)";
  std::string floatingPointRegExp = integerRegExp + "\\.(\\d+)";
  std::string ieee754indexRegExp  = integerRegExp + "|(" + floatingPointRegExp + ")[Ee]" + integerRegExp;
  std::string integerPartString, decimalPartString, exponentialPartString;
  std::smatch integerMatcher, decimalMatcher, exponentialMatcher;
  auto        ret_exp = std::regex_match(inputString, exponentialMatcher, std::regex(ieee754indexRegExp));
  auto        ret_fp  = std::regex_match(inputString, decimalMatcher, std::regex(floatingPointRegExp));
  auto        ret_int = std::regex_match(inputString, integerMatcher, std::regex(integerRegExp));
  if (ret_exp) {
    *type = 3;
    debug_print(exponentialMatcher);
    exponentialPartString=exponentialMatcher[5];
  }
}

void StrToComplex(const std::string& inputString, const vector<std::complex<double>>& outputComplexVector)
{
  assert(inputString.size() <= outputComplexVector.size());
  int tempDigit=0;
  for (int i = 0; i < inputString.size(); i++) {
    tempDigit=(char)inputString[i]-'0';
    outputComplexVector[i].real((double)tempDigit);
    outputComplexVector[i].imag(0.0);
  }

}

int main(int argc, const char** argv)
{
  std::string s = "123.45e678";
  vector<std::complex<double>> integerPartComplexVector = {0, 0};
  vector<std::complex<double>> decimalPartComplexVector = {0, 0};
  vector<std::complex<double>> indexPartComplexVector = {0, 0};
  int                          type                     = 0;
  parseToString(s, integerPartComplexVector, decimalPartComplexVector, indexPartComplexVector, &type);
  return 0;
}
```

**Logs**

[clangd-log.txt](https://github.com/clangd/clangd/files/9641100/clangd-log.txt)

**System information**

System information

Output of clangd --version:
```bash
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
Editor/LSP plugin:

VSCode clangd extension v0.1.21

Operating system:
WSL Linux
5.10.102.1-microsoft-standard-WSL2

**Comment by KagaJiankui** [comment]
Error log with the freshly installed Clangd-15.0.1 from the `install clangd server` command in VSCode:
[clangd-log.txt](https://github.com/clangd/clangd/files/9641192/clangd-log.txt)

**Comment by sam-mccall** [comment]
This sounds serious, but I can't reproduce it. It likely depends on what's in debug_print.h and your standard library.
Is it possible to reduce this to a file without dependencies? (e.g. by copying in the needed bits)

**Comment by KagaJiankui** [comment]
No，the clangd doesn't crash on the other smaller files under the same directory, but it crashes when analyzing the standard libraries like limits.h and iostream.



发自我的小米
在 Sam McCall ***@***.***>，2022年9月26日 11:02写道：

This sounds serious, but I can't reproduce it. It likely depends on what's in debug_print.h and your standard library.
Is it possible to reduce this to a file without dependencies? (e.g. by copying in the needed bits)

**Comment by KagaJiankui** [comment]
[project1.zip](https://github.com/clangd/clangd/files/9643354/project1.zip)
This is the whole working directory that causes the fatal error. And the clangd server only crashes when analyzing the largest file `main.cpp`, while not crashing on `debug_print.cpp` and any other file.

**Comment by KagaJiankui** [comment]
My clangd arguments:
```json
"clangd.arguments": [
        "--all-scopes-completion",
        "--background-index",
        "--clang-tidy",
        "--completion-parse=auto",
        "--completion-style=detailed",
        "--enable-config",
        "--folding-ranges",
        "--header-insertion-decorators",
        "--header-insertion=iwyu",
        "--malloc-trim",
        "--pch-storage=memory",
        "--pretty",
        "--query-driver=clang*,clang,gcc,g++,*-gcc,*-g++,cl",
        "-j=24"
    ]
```

My clangd config.yaml at ~/.config/clangd/:
```yaml
CompileFlags:                     # Tweak the parse settings
  Add: [-Wall]             # treat all files as C++, enable more warnings
  Remove: -W*                     # strip all other warning-related flags
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
Hover:
  ShowAKA: Yes
Diagnostics:
  ClangTidy:
    Add: [bugprone*,cppcoreguidelines*,performance*,modernize*]
    Remove: [modernize-use-trailing-return-type,modernize-avoid-c-arrays,bugprone-easily-swappable-parameters]
  UnusedIncludes: Strict
```
