### ISSUE TITLE
GCC local function support

### ISSUE THREAD

**Issue by Frityet** [clangd/clangd#1342]
Clangd does not support GCC local functions, showing the error even with `gcc` being used in the `compile_commands.json`

*note: I am well aware of the shortcomings of the local function system, and the security issues it causes, however I must use it in this instance.*

```c
int main()
{
    int f(int x)
    {
        return x * 2;
    }
}
```

<img width="707" alt="Screen Shot 2022-10-19 at 4 02 49 PM" src="https://user-images.githubusercontent.com/25426233/196820513-b46d0642-b204-42eb-838a-a9d4bc312827.png">

Output of `clangd --version`:

```yaml
Homebrew clangd version 15.0.2
Features: mac+xpc
Platform: x86_64-apple-darwin20.6.0
```

Editor/LSP plugin:
VSCode/Clangd

Operating system:
MacOS Big Sur 11.6.7 (20G704)
