### ISSUE TITLE
Using quick fix action to rename an identifier does not rename occurrences in other files

### ISSUE THREAD

**Issue by FancyBanana** [clangd/clangd#1589]
The "change to" fix action does not use "rename" action,  it only changed the identifier it was called on.

**System information**

Output of `clangd --version`:
```
clangd --version
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
Also clangd 15.0.6 that is downloaded with clangd extension in VSCode

Editor/LSP plugin:
VSCode/ llvm-vs-code-extensions.vscode-clangd

Operating system:
Ubuntu 22.04.2 LTS

**Comment by HighCommander4** [comment]
Could you provide a code example please, and indicate where in the code you are performing the code action?

**Comment by FancyBanana** [comment]
Here's some example code that has this issue:

**ExampleClass.hpp**
```c++
#pragma once

class test {

    public:

    test();

    float ThisIsAVariable;

    float ThisIsAFunction(float);

};
```

**ExampleClass.cpp**
```c++
#include "ExampleClass.hpp"

test::test() : ThisIsAVariable(1) {};

float test::ThisIsAFunction(float b){
    return ThisIsAVariable * 2 - b;
}
```


**main.cpp**
```c++
#include "ExampleClass.hpp"
#include <iostream>

int main() {


  std::cout << "test " << test().ThisIsAFunction(22) << std::endl;

}
```

**.clang-tidy**
```yaml
Checks: "bugprone-*,
  modernize-*,
  -modernize-use-trailing-return-type,
  -modernize-use-using,
  readability-*,
  clang-analyzer-*,
  clang-diagnostic-*,
  cppcoreguidelines-*,
  -cppcoreguidelines-owning-memory,
  performance-*,
  -fuchsia-*,
  -*-use-auto,
  -cert-err58-cpp,
  -google-readability-todo,
  "
HeaderFilterRegex: ".*"
CheckOptions:
  - {key: readability-implicit-bool-conversion.AllowPointerConditions, value: 1}
  - { key: readability-identifier-naming.NamespaceCase,                value: CamelCase }
  - { key: readability-identifier-naming.TypedefCase,                  value: CamelCase }
  - { key: readability-identifier-naming.TypedefSuffix,                value: _t }
  - { key: readability-identifier-naming.TypeAliasCase,                value: CamelCase }
  - { key: readability-identifier-naming.TypeAliasSuffix,              value: _t }
  - { key: readability-identifier-naming.ClassCase,                    value: CamelCase}
  - { key: readability-identifier-naming.TemplateCase,                 value: CamelCase}
  - { key: readability-identifier-naming.TemplatePrefix,               value: T}
  - { key: readability-identifier-naming.StructCase,                   value: CamelCase }
  - { key: readability-identifier-naming.AbstractClassCase,            value: CamelCase}
  - { key: readability-identifier-naming.AbstractClassPrefix,          value: I}
  - { key: readability-identifier-naming.PrivateMemberCase,            value: CamelCase }
  - { key: readability-identifier-naming.PrivateMemberPrefix,          value: m_ }
  - { key: readability-identifier-naming.ProtectedMemberCase,          value: CamelCase }
  - { key: readability-identifier-naming.ProtectedMemberPrefix,        value: m_ }
  - { key: readability-identifier-naming.PublicMemberCase,             value: camelBack}
  - { key: readability-identifier-naming.ParameterCase,                value: camelBack }
  - { key: readability-identifier-naming.LocalVariable,                value: camelBack}
  - { key: readability-identifier-naming.ConstantCase,                 value: CamelCase}
  - { key: readability-identifier-naming.ConstantPrefix,               value: c_}
  - { key: readability-identifier-naming.EnumCase,                     value: CamelCase}
  - { key: readability-identifier-naming.EnumConstantCase,             value: CamelCase }
  - { key: readability-identifier-naming.ProtectedMethodCase,          value: camelBack }
  - { key: readability-identifier-naming.PublicMethodCase,             value: camelBack}
  - { key: readability-identifier-naming.PrivateMethodCase,            value: camelBack}
  - { key: readability-identifier-naming.PrivateMethodPrefix,          value: _}
  - { key: readability-identifier-naming.MacroDefinitionCase,          value: UPPER_CASE }
```
The issue happens when you try to do the auto fix (or just fix) `float ThisIsAVariable` or `float ThisIsAFunction(float);` in **ExampleClass.hpp**
