### ISSUE TITLE
Multiple `Remove:` lines do not work as I expected for `CompileFlags:`

### ISSUE THREAD

**Issue by siegel** [clangd/clangd#1590]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

My `.clangd` file has the following `CompileFlags:` configuration:

```
CompileFlags:
  Remove: [-index-store-path, -MMD, -MT, -MF, -clang-vendor-feature=*, -fno-odr-hash-protocols, -fmodules, -gmodules, -fmodules-cache-path=*, -fmodules-prune-after=*, -fmodules-validate-once-per-build-session, -fmodules-prune-interval=*, -fbuild-session-file=*, -ivfsstatcache, -analyzer-tidy-checker=*]
```

I find this hard to read, so I had the idea to break it up into multiple entries:

```
CompileFlags:
  Remove: [-index-store-path, -MMD, -MT, -MF, -clang-vendor-feature=*, -fno-odr-hash-protocols]
  Remove: [-fmodules, -gmodules, -fmodules-cache-path=*, -fmodules-prune-after=*, -fmodules-validate-once-per-build-session, -fmodules-prune-interval=*, -fbuild-session-file=*]
  Remove: [-ivfsstatcache, -analyzer-tidy-checker=*]
```

After this change, clangd reported diagnostics corresponding to unrecognized argument flags for *every* argument beginning with `-fmodules`. It appears to have ignored all of the `Remove:` lines after the first one.

What I was expecting is that the options from multiple `Remove:` lines would be aggregated and all of the options ignored.

**Logs**

n/a

**System information**

Output of `clangd --version`:
```
Homebrew clangd version 15.0.7
Features: mac+xpc
Platform: arm64-apple-darwin22.4.0
```

Editor/LSP plugin: BBEdit 14.6.5

Operating system: macOS 13.3.1 (22E261)
