### ISSUE TITLE
No member named 'endl' in namespace 'std'clang(no_member) in *.cu

### ISSUE THREAD

**Issue by davidxiaozhi** [clangd/clangd#1610]
clang prompts me when I use functions or containers in the std namespace in *.cu  **No member named 'endl' in namespace 'std'clang(no_member)** 

```c++
void GPUCache::Query(const key_type *d_keys, const size_t len, float *d_values, uint64_t *d_missing_index, key_type *d_missing_keys, size_t *d_missing_len) {
    cache->Query(d_keys, len, d_values, d_missing_index, d_missing_keys, d_missing_len, stream);
    if (GPUCache::get_print_log()) { std::cout << "========================query==================\n" << std::endl; }
}
```
my file  .clangd

```
#https://clangd.llvm.org/config#compileflags
CompileFlags:
  Add: [ '-std=c++17']
  Remove: [-ccbin=*,-rdc=*,-gencode]

```
