### ISSUE TITLE
can we set different compile-commands-dir for different task?

### ISSUE THREAD

**Issue by HaoLiuHust** [clangd/clangd#1733]
is there a way to set different compile-commands-dir to different task since a project may have a few build folder

**Comment by HighCommander4** [comment]
If you mean different compile_commands.json files for different subdirectories, you can do it with [PathMatch](https://clangd.llvm.org/config.html#pathmatch) and [CompilationDatabase](https://clangd.llvm.org/config.html#compilationdatabase) in the clangd config file. For example:

```yaml
If:
  PathMatch: target1

CompileFlags:
  CompilationDatabase: target1-build

---

If:
  PathMatch: target2

CompileFlags:
  CompilationDatabase: target2-build
```

Now, files under `target1/` will use `target1-build/compile_commands.json`, and files under `target2/` will use `target2-build/compile_commands.json`.
