### ISSUE TITLE
Support environment variable in config file

### ISSUE THREAD

**Issue by Freed-Wu** [clangd/clangd#1827]
`~/.config/clangd/config.yaml`:

```yaml
CompileFlags:
  Add:
    - -I${HOME}/.local/include
```

Comes from <https://github.com/clangd/clangd/discussions/1065#discussioncomment-7555844>.

@HighCommander4 I want to listen your arguments for both and against it :smile:
