### ISSUE TITLE
Help users configure clangd to find standard library headers

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1896]
One of the most common user questions is "how do I get clangd to resolve my standard library headers". I would like to suggest that clangd do more to help users specify the configuration options necessary to find standard library headers.

The first step would be to detect this scenario. That should be fairly simple: if there are any unresolved includes in the current file, check the spellings of the unresolved includes against a list of known standard library headers; if there is a match, we are in this scenario.

Having detected this scenario, clangd could offer one of two prompts under the following conditions:

 1. If (`CompileFlags: Compiler:` is not specified in the config file) **and** ((there is no `compile_commands.json` file) **or** (the compiler path in `compile_commands.json` file is not a full path)): prompt the user to specify the full path of the compiler they are using in `CompileFlags: Compiler:`.
 2. If (we have a full path to a driver) **and** ((the user did not specify `--query-driver`) **or** (the argument to `--query-driver` does not match the actual driver path)): prompt the user to specify `--query-driver=<path>` where `<path>` is the actual driver path for the current file.

**Comment by JoydeepMallick** [comment]
Yes this would be very helpful for new users, well I figured out how to resolve modules not found error by adding the following code in `config.yml` file inside clangd folder :-

```yml
#The file you need to edit is located in :-
#   For Windows based systems : C:\Users\Yourusername\clangd\config.yaml
#   For Linux/unix based systems : ~/.config/clangd/config.yaml
#
#   Note that for both  windows and linux/unix based systems when specifying location to directories to be added to clangd use forward-slashes(/) as seperation between directories  
#   i.e. Windows : C:/Name/......
#        Linux/Unix : /usr/......
#
# In below config 3 include directories have been added:-
# First one denotes location to iostream,.... files specific to "my" mingw64
# 
# Second one denotes location to "bits" directory containing stdc++.h file meaning my stdc++.h file is at "C:/Program Files/mingw64/include/c++/12.1.0/bits/stdc++.h"
#
# Third one denotes location to files like assert.h, .....
#
# That invaluable advice 😱:- https://github.com/clangd/clangd/issues/617#issuecomment-1754846581

CompileFlags:
  Add:
    - --include-directory=C:/Program Files/mingw64/include/c++/12.1.0/
    - --include-directory=C:/Program Files/mingw64/include/c++/12.1.0/x86_64-w64-mingw32/
    - --include-directory=C:/Program Files/mingw64/x86_64-w64-mingw32/include/

```

and this solves most issues regarding `bits/stdc++.h` , `vector`, ..... not found errors.

## Issue
 but I recently noticed autosuggestion of headers specific to location `C:/Program Files/mingw64/include/c++/12.1.0/` is not detected which contains `iostream` and others files. 

Below image shows the bits folder which does not contain stdc++.h file.

![iostream](https://github.com/clangd/clangd/assets/94801952/7bff415f-631f-4372-a6cc-bfd123b49dcb)


Below image contains bits folder containing stdc++.h file.  Can 2 `bits` folder cause conflict?

![stdc++](https://github.com/clangd/clangd/assets/94801952/4679c661-40d1-46b2-8b42-f4beef9c8862)
