### ISSUE TITLE
"iostream" and related headers not detected by clangd even  after setup of config.yml

### ISSUE THREAD

**Issue by JoydeepMallick** [clangd/clangd#1897]
### Problem

I figured out how to resolve modules not found error by adding the following code in `config.yml` file inside clangd folder :-

```yml
#The file you need to edit is located in :-
#   For Windows based systems : C:\Users\Yourusername\clangd\config.yaml
#   For Linux/unix based systems : ~/.config/clangd/config.yaml
#
#   Note that for both  windows and linux/unix based systems when specifying location to directories to be added to clangd use forward-slashes(/) as seperation between directories  
#   i.e. Windows : C:/Name/......
#        Linux/Unix : /usr/......
#
# In below config 3 include directories have been added:-
# First one denotes location to iostream,.... files specific to "my" mingw64
# 
# Second one denotes location to "bits" directory containing stdc++.h file meaning my stdc++.h file is at "C:/Program Files/mingw64/include/c++/12.1.0/bits/stdc++.h"
#
# Third one denotes location to files like assert.h, .....
#
# That invaluable advice 😱:- https://github.com/clangd/clangd/issues/617#issuecomment-1754846581

CompileFlags:
  Add:
    - --include-directory=C:/Program Files/mingw64/include/c++/12.1.0/
    - --include-directory=C:/Program Files/mingw64/include/c++/12.1.0/x86_64-w64-mingw32/
    - --include-directory=C:/Program Files/mingw64/x86_64-w64-mingw32/include/

```

and this solves most issues regarding `bits/stdc++.h` , `vector`, ..... not found errors.

## Issue
 but I recently noticed autosuggestion of headers specific to location `C:/Program Files/mingw64/include/c++/12.1.0/` is not detected which contains `iostream` and others files. 

Below image shows the bits folder which does not contain stdc++.h file.

![iostream](https://github.com/clangd/clangd/assets/94801952/7bff415f-631f-4372-a6cc-bfd123b49dcb)

Below image contains bits folder containing stdc++.h file.  Can 2 `bits` folder cause conflict?

![stdc++](https://github.com/clangd/clangd/assets/94801952/4679c661-40d1-46b2-8b42-f4beef9c8862)

### Am I doing something wrong or is this is a problem?

**System information**
Intel Pentium 2020M
4096MB ram

**Output of `clangd --version`:**
clangd version 16.0.0
Features: windows
Platform: x86_64-pc-windows-msvc

**Editor**
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb  1 2023 23:53:02)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1273
Compiled by appveyor@APPVEYOR-VM
Huge version with GUI.

**LSP plugin:**
Coc-clangd from coc.nvim

**Operating system:**
Windows 10 Enterprise 64 bit version 22H2

**Comment by HighCommander4** [comment]
> but I recently noticed autosuggestion of headers specific to location `C:/Program Files/mingw64/include/c++/12.1.0/` is not detected which contains `iostream` and others files.

Can you elaborate on this to help me understand what you mean?

Please provide a code example and say:
 * what editor action you're performing
 * what you expect to happen
 * what actually happens

**Comment by JoydeepMallick** [comment]
I tried to explain my problem in below:-

https://github.com/clangd/clangd/assets/94801952/71833b05-1172-4243-b107-d7d1f49aa8a1




**Problem**
autosuggestion of iostream and files in location  `C:/Program Files/mingw64/include/c++/12.1.0/` seems to not work while rest works fine.

**Expectation**
iostream must be autosuggested.

Is this a issue form my side, I am a little confused why this is happening.

**Comment by HighCommander4** [comment]
Thanks, I understand the problem now.

The cause is that code completion only offers headers with no file extension in "system" include directories, and you are specifying the standard library include paths using the `--include-directory` flag which makes them "regular" include directories.

You could work around this by using the `-isystem` flag instead of `--include-directory` (but be aware that `-isystem` has a different syntax; I _think_ the way to do it would be to write `-isystemC:/Program Files/mingw64/include/c++/12.1.0/` with no separator, but I haven't tried it and I'm not on Windows to try it.)

---

**However**, I would recommend against trying to manually specify include directories in this way.

A much better way to do this is to use `--query-driver` as illustrated in [this comment](https://github.com/clangd/clangd/issues/617#issuecomment-1763210235). Have you tried that?

**Comment by JoydeepMallick** [comment]
> Thanks, I understand the problem now.
> 
> The cause is that code completion only offers headers with no file extension in "system" include directories, and you are specifying the standard library include paths using the `--include-directory` flag which makes them "regular" include directories.
> 
> You could work around this by using the `-isystem` flag instead of `--include-directory` (but be aware that `-isystem` has a different syntax; I _think_ the way to do it would be to write `-isystemC:/Program Files/mingw64/include/c++/12.1.0/` with no separator, but I haven't tried it and I'm not on Windows to try it.)

Yes your suggestion worked wonders😱💖 now finally I get autocompletion of system headers, so like inside of `...\include\c++\12.1.0\` all files are referred to as system headers? Well I would like to know more about those related terms, 😅, can you suggest me something regarding?. Well here is the below `config.yaml` file for windows system which tackles the issue.

```yaml
#The file you need to edit is located in :-
#   For Windows based systems : C:\Users\Yourusername\clangd\config.yaml
#   For Linux/unix based systems : ~/.config/clangd/config.yaml
#
#   Note that for both  windows and linux/unix based systems when specifying location to directories to be added to clangd use forward-slashes(/) as seperation between directories  
#   i.e. Windows : C:/Name/......
#        Linux/Unix : /usr/......
#
# In below config 3 include directories have been added:-
# First one denotes location to iostream,.... files specific to "my" mingw64
# 
# Second one denotes location to "bits" directory containing stdc++.h file meaning my stdc++.h file is at "C:/Program Files/mingw64/include/c++/12.1.0/bits/stdc++.h"
#
# Third one denotes location to files like assert.h, .....
#
# That invaluable advices 😱:- https://github.com/clangd/clangd/issues/617#issuecomment-1754846581 , https://github.com/clangd/clangd/issues/1897#issuecomment-1878279529
#
# IMPORTANT :-
#
# 1. --include-directory flag makes them "regular" include directories.
# 2. code completion only offers headers with no file extension in "system" include directories.Work around this by using the -isystem flag instead of --include-directory

CompileFlags:
  Add:
    - -isystemC:/Program Files/mingw64/include/c++/12.1.0/
    - --include-directory=C:/Program Files/mingw64/include/c++/12.1.0/x86_64-w64-mingw32/
    - --include-directory=C:/Program Files/mingw64/x86_64-w64-mingw32/include/

```




> **However**, I would recommend against trying to manually specify include directories in this way.
> 
> A much better way to do this is to use `--query-driver` as illustrated in [this comment](https://github.com/clangd/clangd/issues/617#issuecomment-1763210235). Have you tried that?

Regarding this my equivalent codeblock for  `config.yaml` is

```yaml
CompileFlags:
Compiler: C:\Program Files\mingw64\bin\g++.exe

```

this gives me autocompletion for most files but not those like `iostream` and files in that directory, I did not need to perform step 2 of [your comment](https://github.com/clangd/clangd/issues/617#issuecomment-1763210235).  

### **One doubt**
I have only added g++.exe for now, how to add the other one, gcc.exe in yaml file?


##performing step 2
Also as you mentioned in step 2 of [your comment](https://github.com/clangd/clangd/issues/617#issuecomment-1763210235) what should be the gvim coc equivalent?

If I guessed it right I placed it under `coc-settings.json` file which can be accessed via `:CocConfig` in vim command line. The file I updated is given below :-

```json
{
  "coc.preferences.formatOnSaveFiletypes": [
    "css",
    "markdown",
    "javascript",
    "typescript",
    "typescriptreact",
    "json",
    "javascriptreact",
    "typescript.tsx",
    "graphql"
  ],
  "suggest.noselect": true,
  "snippets.ultisnips.pythonPrompt": false,

  "python.pythonPath": "C:\\Users\\JOYDEEP\\AppData\\Local\\Programs\\Python\\Python310\\python.exe",
  "python.formatting.provider": "black",

  "clangd.path": "~\\AppData\\Local\\coc\\extensions\\coc-clangd-data\\install\\16.0.2\\clangd_16.0.2\\bin\\clangd.exe",

  "clangd.arguments": [
    "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe",
    "--query-driver=C:\\Program Files\\mingw64\\bin\\gcc.exe"
  ]
}

```

Yet autocompletion to files like `iostream` could not be achieved, rather it seems to have no effect rather on anything.

But you `isystem` suggestion works👍🏼.


## my prediction
I guess if I combine the compiler and add flags in this way like :- 

```yaml
CompileFlags:
Compiler: C:\Program Files\mingw64\bin\g++.exe

Add:
 - -isystemC:/Program Files/mingw64/include/c++/12.1.0/
```

it should work though I have not tested it yet.

**Comment by HighCommander4** [comment]
> so like inside of `...\include\c++\12.1.0\` all files are referred to as system headers? Well I would like to know more about those related terms, 😅, can you suggest me something regarding?

I believe the distinction between "system" includes paths vs. regular ones comes from gcc, you can read about it at https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html. Clang generally tries to be compatible with gcc and so follows the same conventions.

Code completion only offering headers with no extensions in system include paths is a choice made by clangd. The idea behind it is that headers without extensions are mostly only used by the standard library; in a project's include directory, a file without an extension is more likely to be some other file type (e.g. not a source file at all) and offering code completion for it would just add noise.

> Regarding this my equivalent codeblock for `config.yaml` is
> 
> ```yaml
> CompileFlags:
> Compiler: C:\Program Files\mingw64\bin\g++.exe
> ```

(This may just be a formatting issue, but note that `Compiler` needs to be indented relative to `CompileFlags:`.)

> I have only added g++.exe for now, how to add the other one, gcc.exe in yaml file?

You only need both if you have a mixture of C and C++ files in a single project.

If that's the case, you can use the config file's `If:` feature. See [this answer](https://stackoverflow.com/a/76286667) for an example of that.

> ```json
>   "clangd.arguments": [
>     "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe",
>     "--query-driver=C:\\Program Files\\mingw64\\bin\\gcc.exe"
>   ]
> ```

I don't think that works, the second argument will override the first one. Instead, this should work:

```json
"clangd.arguments": [
  "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe,C:\\Program Files\\mingw64\\bin\\gcc.exe"
]
```

> Yet autocompletion to files like `iostream` could not be achieved, rather it seems to have no effect rather on anything.

Please feel free to share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) and I'm happy to help troubleshoot further.

**Comment by JoydeepMallick** [comment]
> (This may just be a formatting issue, but note that `Compiler` needs to be indented relative to `CompileFlags:`.)

🔥Absolutely right! Indenting solved the issue, now my config.yaml contains :-
```yaml
CompileFlags:
  Compiler: C:\Program Files\mingw64\bin\g++.exe

```
and coc-settings.json contains:-

```json
....
....
  "clangd.arguments": [
     "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe,C:\\Program Files\\mingw64\\bin\\gcc.exe"
   ]
....
....
```
✅now I do get autocompletions regarding iostream and all system header files without any issue, thanks!



> > so like inside of `...\include\c++\12.1.0\` all files are referred to as system headers? Well I would like to know more about those related terms, 😅, can you suggest me something regarding?
> 
> I believe the distinction between "system" includes paths vs. regular ones comes from gcc, you can read about it at https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html. Clang generally tries to be compatible with gcc and so follows the same conventions.
> 
> Code completion only offering headers with no extensions in system include paths is a choice made by clangd. The idea behind it is that headers without extensions are mostly only used by the standard library; in a project's include directory, a file without an extension is more likely to be some other file type (e.g. not a source file at all) and offering code completion for it would just add noise.
> 
> > Regarding this my equivalent codeblock for `config.yaml` is
> > ```yaml
> > CompileFlags:
> > Compiler: C:\Program Files\mingw64\bin\g++.exe
> > ```
> 
> (This may just be a formatting issue, but note that `Compiler` needs to be indented relative to `CompileFlags:`.)
> 
> > I have only added g++.exe for now, how to add the other one, gcc.exe in yaml file?
> 
> You only need both if you have a mixture of C and C++ files in a single project.
> 
> If that's the case, you can use the config file's `If:` feature. See [this answer](https://stackoverflow.com/a/76286667) for an example of that.
> 
> > ```json
> >   "clangd.arguments": [
> >     "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe",
> >     "--query-driver=C:\\Program Files\\mingw64\\bin\\gcc.exe"
> >   ]
> > ```
> 
> I don't think that works, the second argument will override the first one. Instead, this should work:
> 
> ```json
> "clangd.arguments": [
>   "--query-driver=C:\\Program Files\\mingw64\\bin\\g++.exe,C:\\Program Files\\mingw64\\bin\\gcc.exe"
> ]
> ```
> 
> > Yet autocompletion to files like `iostream` could not be achieved, rather it seems to have no effect rather on anything.
> 
> Please feel free to share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) and I'm happy to help troubleshoot further.


Well this solution might prevent code mixing if I am not wrong which is why we refer files as C/C++ more often and sometimes people  tend to use `ios::sync_with_stdio(false)` to avoid synchronization in code.

Upon updating my config.yaml file :- 
```yaml
If:
  PathMatch: .*\.(cpp|cc|cxx)
CompileFlags:
  Compiler: C:\Program Files\mingw64\bin\g++.exe
  Add: [-std=c++20]
  
---

If:
  PathMatch: .*\c
CompileFlags:
  Compiler: C:\Program Files\mingw64\bin\gcc.exe
  Add: [-std=c17]

```

For C++ files all headers are suggested, but specifically for `.c` files like iostream,...... are not suggested since they are not specific to C headers I suppose.




> Please feel free to share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) and I'm happy to help troubleshoot further.

Well I could not figure out how to share clangd logs.
