### ISSUE TITLE
Support specifying diagnostic severity for categories of diagnostics in config file

### ISSUE THREAD

**Issue by 5chmidti** [clangd/clangd#1937]
After llvm/llvm-project@a59b24b, deprecation warnings (that also includes clang-tidy `modernize` and `misc-unused` checks) are downgraded to remarks, which results in low visibility of issues in vscode (maybe others as well).
![image](https://github.com/llvm/llvm-project/assets/44101708/e66b4fc8-7e3a-4edb-8fbe-602bdce4a969)

The issue was also raised in clangd/vscode-clangd#482. See also llvm/llvm-project#75706.

I think the best way to provide users what they want, be it reducing signal-to-noise ratio when there are a lot of warnings or keeping the warning severity of diagnostics, is the best way forward.

```yaml
Diagnostics:
  Severity:
    Deprecated: Error
    Unused: Warning
    [Tidy]Modernize: Info
    [Tidy]Misc: Remark
```

The `Deprecated` group would map to the compiler warnings that are categorized as deprecated [here](https://github.com/llvm/llvm-project/blob/f49e2b05bf3ececa2fe20c5d658ab92ab974dc36/clang-tools-extra/clangd/Diagnostics.cpp#L343). The `Unused` group would map similar to its categorized warnings.
The clang-tidy checks would map to their module name, however, that would lead to all of `misc` to be categorized, without support for `misc-unused` like it is [currently defined](https://github.com/llvm/llvm-project/blob/f49e2b05bf3ececa2fe20c5d658ab92ab974dc36/clang-tools-extra/clangd/Diagnostics.cpp#L393).
Supporting matching prefixes (but that instantly suggests supporting wildcards) could help:
```yaml
Diagnostics:
  Severity:
    Warnings:
      Deprecated: Error
      Unused: Warning
    Tidy:
      modernize: Info
      misc: Remark
      misc-unused: Error
```

There is also the question of how to support deprecation warnings in strike-through form (see picture). The above approach only lets you set the diagnostic severity. I personally don't think strike-through needs to be controllable, but others might want this option as well.
