### ISSUE TITLE
Adding include through code-actions uses absolute paths

### ISSUE THREAD

**Issue by jeroen-dhollander** [clangd/clangd#2010]
**Problem**

There are 3 ways to ask clangd to add includes, and each one gives a different result wrt absolute vs relative paths:
   * Through auto-completion: **correct**: path relative to project root is picked
   * Through quick-fix action: **wrong** path relative to local directory is picked
   * Through code-action 'fix all includes': **wrong** absolute path is picked

**Example**:

I am working in chromium/src, in the [device_command_start_crd_session_job.cc file](https://crgo.dev/c/b/ash/policy/remote_commands/crd/device_command_start_crd_session_job.cc;l=42).
The symbol `StartCrdSessionJobDelegate` is used but not included.

If I auto-complete after `StartCrdSessionJobDelega` and have that add the include clangd adds

```
#include "chrome/browser/ash/policy/remote_commands/crd/start_crd_session_job_delegate.h"
```

If I stand on the symbol and trigger quick fix clangd adds

```
#include "start_crd_session_job_delegate.h"
```

If I stand on the symbol and trigger the fix all includes code-action clangd adds

```
#include "/usr/local/google/home/<snip>/chromium2/src/components/policy/core/common/remote_commands/remote_command_job.h"
```

**Logs**

Attached. 
[clangd.log](https://github.com/clangd/clangd/files/14976028/clangd.log)

**Configuration**

```
╰─❮ head -n20 ~/.config/clangd/config.yaml
# Various settings, from https://clangd.llvm.org/config.html
#
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict

# Inlay hints
InlayHints:
  Enabled: Yes
  # No inlay hints for function parameters, e.g. my_function(value: "abc")
  ParameterNames: No
  # Shows inlay hints for 'auto'.
  DeducedTypes: Yes
```

**System information**

Output of `clangd --version`:

```
╰─❯ clangd --version
clangd version google3-trunk (1e6ce5e284f5c0e8d64eee21af727bb164eb3caf)
Features: linux+grpc
Platform: x86_64-grtev4-linux-gnu
```

Editor/LSP plugin:

neovim with Coc completion 

Operating system:

Linux
