### ISSUE TITLE
clangd loaded unexpected compilation database when multiple instances were launched.

### ISSUE THREAD

**Issue by zhang-stephen** [clangd/clangd#2060]
Clangd has loaded different compilation database from different instances.

There are 2 workspaces you will see in the log, for working on different branches and different targets:
- `/host/workdir/l1sw` for x86 native, compilation database location is `out/build-thor-gcc64`,
- `/host/workdir/l1sw-git` for aarch64 cross-compile, compilation database location is `out/build-thor-arm`,

Then I opened them in VSCode, and I found the aarch64 compilation database was loaded in the vscode session for the x86 native. You could see the compilation database from aarch64 was loaded in the attached log.

![image](https://github.com/clangd/clangd/assets/17326718/242eff6f-ec9b-4085-bbda-b660799840b3)

*This log was collected in the vscode session for x86 native*.

And here are 2 clangd instances:

![image](https://github.com/clangd/clangd/assets/17326718/7fe67fda-603f-4f10-be95-a270745345da)

The minimal project configuration of clangd:
```yaml
---
CompileFlags:
  Add:
    # compile flags
    - -xc++
    - -std=c++20

    # system include path(llvm only) # these paths should be updated with LLVM upgrades
    - -isystem
    - /opt/llvm-16.0_044/include/c++/v1

    - -isystem
    - /opt/llvm-16.0_044/include/x86_64-unknown-linux-gnu/c++/v1
  Remove:
    - -std=gnu++2*
    - -m*
    - -f*
    - -W*
  CompilationDatabase: out/build-thor-gcc64
  Compiler: /usr/bin/c++
```

And it causes many unexpected error reports, completion not work, and other unexpected behaviors. I guess it might be communication issues between vscode-clangd and the clangd server itself, or clangd cannot handle multiple instances. 

**Logs**
[clangd_logs.txt](https://github.com/user-attachments/files/15528393/clangd_logs.txt)

**System information**

Output of `clangd --version`:
```
clangd version 16.0.6 (gitlab@gitlab.dynamic.nsn-net.net:clang/llvm-project.git e0b865882caf58524a99ab5f85699c1f31dd9191)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
VSCode 1.89.1 and vscode-clangd, latest

Operating system:
Windows 11, CentOS 7.9(remote)
