### ISSUE TITLE
clang-tidy `AllowInternalLinkage` option for non-const global variables still flags static variables when enabled

### ISSUE THREAD

**Issue by recursivenomad** [clangd/clangd#2135]
When `AllowInternalLinkage` is set to true, clang-tidy still warns me about static non-const "global" variables.

```yaml
#config.yaml

Diagnostics:
  ClangTidy:
    Add: "*"
    CheckOptions:
      cppcoreguidelines-avoid-non-const-global-variables.AllowInternalLinkage: true
```

```c
// main.c

static unsigned char foo; // Variable 'foo' is non-const and globally accessible, consider making it const

int main () {
  return 0;
}
```

**System information**

Output of `clangd --version`:
```
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin:
VSCode-Clangd

Operating system:
Windows 10
