### ISSUE TITLE
CompileFlags.Replace

### ISSUE THREAD

**Issue by Freed-Wu** [clangd/clangd#2249]
Now we have

```yaml
---
CompileFlags:
  Add:
    - ...
  Remove:
    - ...
```

Can we have

```yaml
---
CompileFlags:
  Replace:
    original_RE: replaced_RE
    ^-I=: -I
```

For example, some C compiler like TI CGT use `-I=/the/path`, not clang's
`-I/the/path`. we can

```yaml
---
CompileFlags:
  Replace:
    ^-I=: -I
```

to let clangd search correct path, not

```yaml
---
CompileFlags:
  Add:
    - -I.
    - -I..
  Remove:
    - -I=*
```
