### ISSUE TITLE
Get error on .cuh file

### ISSUE THREAD

**Issue by DavidZyy** [clangd/clangd#2294]
clangd get error on `.cuh` file:
```
Unable to handle compilation, expected exactly one compiler job in ''clang(fe_expected_compiler_job)
```
 here is the output of logs.

[a.txt](https://github.com/user-attachments/files/18473728/a.txt)

**Comment by DavidZyy** [comment]
I have see #2092 have the same problem, but it is not solved for the auther not share logs.

**Comment by HighCommander4** [comment]
Have you followed the setup steps at https://clangd.llvm.org/installation#project-setup ?

**Comment by DavidZyy** [comment]
Sorry, I forget it. I add
```
-I./llmc
```
at `compile_flags.txt` and add 
```
If:
  PathMatch: .*\.h

CompileFlags:
  Add: -xc++
```
at `.clangd`, but this project has two types of headers, `.h` and `.cuh`, `.cuh` still has the same error.
And here is the logs:

[a.txt](https://github.com/user-attachments/files/18500910/a.txt)

**Comment by HighCommander4** [comment]
It looks like clang does not know what kind of source file `.cuh` is without the help of a `-x` flag.

Can you try changing `.clangd` to:

```yaml
If:
  PathMatch: .*\.h

CompileFlags:
  Add: -xc++

---

If:
  PathMatch: .*\.cuh

CompileFlags:
  Add: -xcuda
```
