### ISSUE TITLE
not working correctly for C++ and C

### ISSUE THREAD

**Issue by BhJaipal** [clangd/clangd#2393]
Please describe the problem.
When I put -std=c++2b or c++23 this flag still works for C files and 
shows invalid argument -std=c++2b for C

**Logs**

It does not show any error in logs

**System information**

Output of `clangd --version`:

clangd version 19.1.0 (https://github.com/llvm/llvm-project a4bf6cd7cfb1a1421ba92bca9d017b49936c55e4)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
I use neovim + mason for C and C++

Operating system:
I have pop OS Linux as main 

my .clangd file:
```yaml
CompileFlags:
  Add:
    - '-I/usr/include/x86_64-linux-gnu/c++/11'
    - '-I/usr/include/c++/11'
    - '-I/usr/include/c++/11/backward'
    - '-I/usr/include/c++/11/bits'
    - '-I/usr/include/c++/11/ext'
    - '-I/usr/include/c++/11/debug'
    - '-I/usr/include/c++/11/experimental'
    - '-std=gnu++2b'
```
