### ISSUE TITLE
Provide a way to ignore files

### ISSUE THREAD

**Issue by haferburg** [clangd/clangd#588]
Sometimes I open a file which is not part of the project that I'm developing, just for reference. E. g. I want to look up something in an old project, or because it contains documentation.

Whatever the reason, `clangd` will then try and fail to process this file, because it doesn't have the right compiler flags.

What I'd like to see is some way to prevent clangd from doing that. The way I see it is that I already provided a `compile_commands.json` file that specifies which files I consider part of the project. Could we have a way to tell the server that it should ignore any file not listed? Maybe as part of the `initializationOptions`.

I'm not sure if this should be a feature of the server or the client. Please let me know what you think.

I'm using clangd together with the LSP plugin for Sublime Text 3.

**Comment by arr2036** [comment]
@haferburg you closed this issue... Did you find an existing way to do this? I'm experiencing the same problem.  clangd keeps indexing files outside of the project which produce many errors and cause clangd to become unresponsive... I've added an ignore rule in `.clangd` but the indexer still finds them somehow.

```
# osmocom code has many errors/warnings and seems to lock up clangd
If:
  PathMatch: .*/rlm_sigtran/(libosmo|asn1).*
Index:
  Background: Skip
```
