### ISSUE TITLE
Specify compiler to query in config file

### ISSUE THREAD

**Issue by rapgenic** [clangd/clangd#642]
I think it would be useful to be able to specify which compiler to query, along with the compilation flags in the .clangd config file.

```yaml
CompileFlags:
  Add:
    - -IC:/Keil_v5/ARM/PACK/ARM/CMSIS/5.0.0/CMSIS/Include
    - -IC:/Keil_v5/ARM/PACK/Keil/STM32F1xx_DFP/2.3.0/Device/Include
    - -IC:/Keil_v5/ARM/ARMCC/include
    - -D__MICROLIB
    - -D_RTE_
    - -DSTM32F10X_MD
    - -DUSE_HAL_DRIVER
    - -DSTM32F103xB    
  Compiler: C:/Keil_v5/ARM/ARMCC/bin/armcc.exe
```

This allows to have the correct paths and flags set correctly even when a compilation commands file is not available

Maybe to be coherent with the `--query-driver` command line option it should be named `QueryDriver` instead of `Compiler` (even though I find it a little confusing)?
