### ISSUE TITLE
clangd config parsing doesn't understand allegedly supported config keys

### ISSUE THREAD

**Issue by CamJN** [clangd/clangd#869]
When trying to configure clangd to use the `compile_commands.json` file in the correct directory, and configure clang-tidy to ignore some acceptable issues in my test codebase, clangd complains that it doesn't know about options that are documented to be supported as far as I can tell.

However, running `strings` on clangd doesn't print the missing config keys:

`strings /Library/Developer/CommandLineTools/usr/bin/clangd | grep -wFe CompilationDatabase -e Diagnostics` yields nothing
`strings /Library/Developer/CommandLineTools/usr/bin/clangd | grep -wFe ClangTidy` does print `ClangTidy` though, which should be nested under `Diagnostics` according to the docs and the example here: https://clangd.llvm.org/faq

**Config**

```
If:
  PathMatch: test/src/.*

CompileFlags:
  CompilationDatabase: "test"

Diagnostics:
  ClangTidy:
    Remove: [readability-magic-numbers,cppcoreguidelines-avoid-non-const-global-variables,cppcoreguidelines-avoid-magic-numbers,portability-restrict-system-includes,llvmlibc-restrict-system-libc-headers,bugprone-reserved-identifier,bugprone-suspicious-include] 
```

**Logs**

```
I[18:06:19.499] Apple clangd version 13.0.0 (clang-1300.0.29.3)
I[18:06:19.500] PID: 57588
I[18:06:19.500] Working directory: /Users/camdennarzt/Developer/C++/getargv
I[18:06:19.500] argv[0]: /Library/Developer/CommandLineTools/usr/bin/clangd
I[18:06:19.500] argv[1]: --header-insertion-decorators=0
I[18:06:19.500] Starting LSP over stdin/stdout
I[18:06:19.500] <-- initialize(56)
I[18:06:19.529] --> reply:initialize(56) 28 ms
I[18:06:19.547] <-- initialized
I[18:06:19.548] <-- textDocument/didOpen
I[18:06:19.548] config warning at /Users/camdennarzt/Developer/C/getargv/.clangd:5:2: Unknown CompileFlags key 'CompilationDatabase'
I[18:06:19.548] config warning at /Users/camdennarzt/Developer/C/getargv/.clangd:7:0: Unknown Config key 'Diagnostics'
...
```

**System information**

- Output of `clangd --version`: `Apple clangd version 13.0.0 (clang-1300.0.29.3)`
  - This version is supposedly based on llvm 12 (https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_(since_SwiftUI_framework)_2)
  - which should support the config keys used: https://clangd.llvm.org/config
- Editor/LSP plugin: emacs lsp-mode 20210911.950
- Operating system: macOS 11.6
