### ISSUE TITLE
.clang-format end with ... can't work

### ISSUE THREAD

**Issue by sink0918** [clangd/clangd#876]
**System information**

Output of `clangd --version`: 12.0.1

Editor/LSP plugin: VS Code

Operating system: WSL 2 Ubuntu 20.04

**Problem**

When I add a `.clang-format` file to the root of workspace, it only works when I remove the last row `...`

My `.clang-format` file is
```
---
Language: Cpp
BasedOnStyle: Google

AccessModifierOffset: -2
AlignAfterOpenBracket: AlwaysBreak
BraceWrapping:
  AfterClass: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
BreakBeforeBraces: Custom
ColumnLimit: 100
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 2
DerivePointerAlignment: false
PointerAlignment: Middle
ReflowComments: false
...
```
When I check https://clang.llvm.org/docs/ClangFormatStyleOptions.html, all the examples end with `...`. So it would be nice if someone could tell me what's wrong with the `...`
